apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  kustomize.buildOptions: --load-restrictor LoadRestrictionsNone --enable-helm
  resource.customizations: |
    v1/Secret:
      ignoreDifferences: |
        jsonPointers:
        - /sops
