apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd.yaml
  - kubemage.yaml
  - cert-manager.yaml
  - monitoring.yaml
  - monitoring-addons.yaml
  - monitoring-crds.yaml
  - dashboard-ingress.yaml
  - gatekeeper.yaml
  - gatekeeper-policies.yaml
  - datastores.yaml
  - messaging.yaml
  - ../security/cert-manager-clusterissuer.yaml
