apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-pool
  namespace: metallb-system
spec:
  addresses:
    - 144.217.149.203/32
    - 149.56.244.16/32
    - 149.56.123.163/32
    - 66.70.152.224/32
    - 142.44.177.171/32
    - 66.70.159.109/32
    - 51.161.21.62/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-advertise
  namespace: metallb-system
spec:
  ipAddressPools:
    - public-pool
