apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bdgy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/EllistonDow/kubemage.git
    targetRevision: main
    path: charts/magento
    helm:
      valueFiles:
        - sites/bdgy-values.yaml
      releaseName: bdgy
  destination:
    server: https://kubernetes.default.svc
    namespace: bdgy
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
