apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../cluster/phase4/namespaces/bdgy.yaml
helmCharts:
  - name: magento
    releaseName: bdgy
    namespace: bdgy
    path: ../../../charts/magento
    valuesFile: values-bdgy.yaml
