apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bdgy
resources:
  - ../../../cluster/phase4/namespaces/bdgy.yaml
helmGlobals:
  chartHome: ../../../charts
helmCharts:
  - name: magento
    releaseName: bdgy
    namespace: bdgy
    valuesFile: values-bdgy.yaml
    valuesFile: values-bdgy.yaml
