apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
  labels:
    kubemage.io/component: alerting
    app.kubernetes.io/name: alertmanager-telegram
stringData:
  token: 8353277901:AAE_6ZFLeFWBxg_zxoUTMqFEuYfaPvTnrvM
