apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - percona-metrics.yaml
  - opensearch-exporter.yaml
  - minio-monitor.yaml
  - rabbitmq-monitor.yaml
  - valkey-exporter.yaml
  - blackbox-exporter.yaml
  - prometheus-rules.yaml
