apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../cluster/phase4/namespaces/demo.yaml
helmGlobals:
  chartHome: ../../../charts
helmCharts:
  - name: magento
    releaseName: demo
    namespace: demo
    valuesFile: values-demo.yaml
    valuesFile: values-demo.yaml
