apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../cluster/phase4/namespaces/demo.yaml
helmCharts:
  - name: magento
    releaseName: demo
    namespace: demo
    path: ../../charts/magento
    valuesFile: values-demo.yaml
