apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../cluster/phase2/security/gatekeeper-pss-template.yaml
  - ../../../../cluster/phase2/security/gatekeeper-pss-constraint.yaml
patchesStrategicMerge:
  - patch-template.yaml
  - patch-constraint.yaml
