apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "magento.fullname" . }}-env
  labels:
    {{- include "magento.labels" . | nindent 4 }}
data:
  BASE_URL: {{ .Values.env.baseUrl | quote }}
  MEDIA_BUCKET: {{ .Values.env.mediaBucket | quote }}
  RABBITMQ_HOST: {{ .Values.env.rabbitmqHost | quote }}
  REDIS_HOST: {{ .Values.env.redisHost | quote }}
  MYSQL_HOST: {{ .Values.env.mysqlHost | quote }}
