apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-databases.yaml
  - namespace-object-storage.yaml
  - secret-percona-secrets.yaml
  - minio-secret.yaml
  - percona-operator-app.yaml
  - percona-cluster-app.yaml
  - percona-grant-super-job.yaml
  - minio-app.yaml
