image:
  web:
    repository: registry.ovh.net/kubemage/magento-web
    tag: 2025.11.01
  php:
    repository: registry.ovh.net/kubemage/magento-php-fpm
    tag: 2025.11.01
  cron:
    repository: registry.ovh.net/kubemage/magento-cron
    tag: 2025.11.01
  pullPolicy: IfNotPresent

env:
  baseUrl: https://store1.example.com
  mediaBucket: s3://store1-media
  rabbitmqHost: magento-mq.messaging.svc.cluster.local
  redisHost: valkey-master.cache.svc.cluster.local
  mysqlHost: magento-db-pxc.databases.svc.cluster.local
  openSearchHost: opensearch.search.svc.cluster.local
  openSearchPort: 9200

remoteStorage:
  driver: aws-s3
  bucket: store1-media
  region: us-east-1
  prefix: media
  endpoint: http://minio.object-storage.svc.cluster.local:9000
  usePathStyle: true

secrets:
  mysqlUser: {{ "bXlfc3RvcmU=" }}
  mysqlPassword: {{ "c3VwZXJzZWNyZXQ=" }}
  mysqlRoot: {{ "cm9vdHNlY3JldA==" }}
  rabbitmqPassword: {{ "cmFiYml0" }}
  redisPassword: {{ "cmVkaXM=" }}
  remoteStorageAccessKey: {{ "QUtJQUpWTUVEQUtJ" }}
  remoteStorageSecretKey: {{ "U2VjdXJlU2VjcmV0S2V5" }}

cron:
  schedules:
    - name: minute
      schedule: "*/1 * * * *"
      command: ["/bin/bash","-c","php bin/magento cron:run"]

consumers:
  enabled: true
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  list:
    - name: async
      queue: async.operations.all
      replicas: 2
      maxMessages: 100

keda:
  rabbitmq:
    enabled: true
    queueName: async.operations.all
    hostSecret: rabbitmq-credentials
    triggerType: rabbitmq

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: store1.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: store1-tls
      hosts:
        - store1.example.com
