apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infra/overlays/prod
  - ../../platform/gitops/argocd.yaml
  - ../../platform/monitoring/kube-prometheus.yaml
  - ../../platform/security/gatekeeper.yaml
  - ../../tenants/store1
