apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # TODO: infra overlay blocked until cluster/phase1 manifests are converted to valid resources
  # - ../../infra/overlays/prod
  - ../../../cluster/operations/shared-backup
  # - ../../tenants/store1
  - ../../tenants/demo
  - ../../tenants/bdgy
