apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ops
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: shared-backup-script
    files:
      - shared-backup.sh=../../../scripts/shared-backup.sh
resources:
  - namespace.yaml
  - pvc.yaml
  - secret.yaml
  - rbac.yaml
  - cronjob.yaml
  - cronjob-upload.yaml
  - cronjob-dropbox.yaml
